"use client"
import './globals.css'
import {Titillium_Web } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
const titillium_Web = Titillium_Web({weight:['300','400','600','700'],preload:false,subsets:['latin'],display:'swap'})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import { ThemeProvider } from '@emotion/react'
import { theme } from '@/styles/theme'
import Header from '@/component/home/header'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={titillium_Web.className}><ThemeProvider theme={theme}>
        <Header/>
        {children}
      </ThemeProvider></body>
    </html>
  )
}
